run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - unconvert
    - unparam

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
